/** Matches server `DEFAULT_APP_BADGE_LABEL`. */
export const DEFAULT_APP_BADGE_LABEL = "Provided by SapAi";

/** Matches server `DEFAULT_EMBED_AI_DISCLAIMER` when the project has no custom override. */
export const DEFAULT_EMBED_AI_DISCLAIMER =
  "Responses are generated by AI and may be inaccurate. Verify important details with official sources.";
